main: me.chocolf.moneyfrommobs.MoneyFromMobs
name: MoneyFromMobs
version: 4.0
api-version: 1.13
author: Chocolf
description: Makes mobs drop money with looting multiplier
depend: [Vault]
softdepend: [WorldEdit,WorldGuard,MythicMobs,PlaceholderAPI,RoseStacker,LorinthsRpgMobs]
commands:
  MfmReload:
    description: Reloads the config file of Money From Mobs
    permission: MoneyFromMobs.reload
    usage: "Usage: /MfmReload"
  MfmDrop:
    description: Drops a specified amount of money on the ground
    permission: MoneyFromMobs.drop
    usage: "Usage: /MfmDrop <AmountToDrop> [NumberOfDrops]"
  MfmMute:
    description: Mutes messages sent by the plugin when a player picks up money
    permission: MoneyFromMobs.mute
    usage: "Usage: /MfmMute"
  MfmClear:
    description: Removes all money drops off the ground
    permission: MoneyFromMobs.clear
    usage: "Usage: /MfmClear"
  MfmEvent:
    description: Starts/Stops an event that increases the amount of money dropped by mobs for a certain amount of time.
    permission: MoneyFromMobs.event
    usage: "Usage: /MfmEvent <Start/Stop> [Percentage Increase] [Hours] [Minutes] [Seconds]"

permissions:
  MoneyFromMobs.use:
    description: Allows players to kill mobs to obtain money and pick money up.
    default: true